-- Requiring all the necessary plugin configuration files that are not lazy loaded
require "user.plugins.lualine"
require "user.plugins.treesitter"
require "user.plugins.toggleterm"
require "user.plugins.comment"
require "user.plugins.nvim-colorizer"
require "user.plugins.indent-blankline"
require "user.plugins.alpha"
require "user.plugins.persistence"
require "user.plugins.gitsigns"
require "user.plugins.nvim-web-devicons"
require "user.plugins.nvim-dap"
require "user.plugins.bufferline"
require "user.plugins.project"
require "user.plugins.illuminate"
require "user.plugins.mason"
