-- Requiring all the necessary plugin configuration files
require "user.plugins.lualine"
require "user.plugins.cmp"
require "user.plugins.lsp"
require "user.plugins.nvim-tree"
require "user.plugins.treesitter"
require "user.plugins.toggleterm"
require "user.plugins.autopairs"
require "user.plugins.comment"
require "user.plugins.nvim-colorizer"
require "user.plugins.indent-blankline"
require "user.plugins.alpha"
require "user.plugins.persistence"
require "user.plugins.gitsigns"
require "user.plugins.nvim-web-devicons"
require "user.plugins.nvim-dap"
require "user.plugins.telescope"
require "user.plugins.bufferline"
